language: node_js
node_js:
    - "0.12"
    - "0.10"
addons:
    apt:
        packages:
            - libpng12-0
            - libgif4
            - libpango1.0-0
            - libpixman-1-0
            - libcairo2
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
